version: '3.8'

services:
  heavyweight_fastapi:
    build: .
    command: bash -c 'while !</dev/tcp/heavyweight_db/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=supersecretkey
      - HASHING_ALGORITHM=HS256
      - POSTGRES_DATABASE_URL=postgresql://heavyweight:backend@heavyweight_db:5432/heavyweight_db
      - MQTT_BROKER=autorack.proxy.rlwy.net
      - MQTT_PORT=35238
    depends_on:
      - heavyweight_db
    networks:
      - heavyweight_network

  heavyweight_db:
    image: postgres:15-alpine
    volumes:
      - heavyweight_volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=heavyweight
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=heavyweight_db
    networks:
      - heavyweight_network
 
  nginx-proxy:
      image: jwilder/nginx-proxy
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - certs:/etc/nginx/certs:ro
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - acme:/etc/acme.sh
      labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
      volumes:
        - certs:/etc/nginx/certs:rw
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - acme:/etc/acme.sh
  www:
      image: nginx
      restart: always
      expose:
        - "80"
      volumes:
        - ./www:/usr/share/nginx/html:ro
      environment:
        - VIRTUAL_HOST=localhost,localhost
        - LETSENCRYPT_HOST=localhost,localhost
        - LETSENCRYPT_EMAIL=pablo@pablokbs.com
      depends_on:
        - nginx-proxy
        - letsencrypt
volumes:
  heavyweight_volume:
  certs:
  html:
  vhostd:
  acme:

networks:
  heavyweight_network: